# Generated by Django 2.2.7 on 2019-11-26 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medignore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='file',
            new_name='photo_file',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='uploaded_at',
        ),
    ]
